/**
 * Shapes of a CMF UI Page export.
 *
 * These are deliberately loose: the export is machine-generated by CMF and we
 * only model the parts the validator reads. Anything not asserted here is left
 * as `unknown` rather than guessed at — the same discipline the generator uses.
 */

export type Level = "FAIL" | "WARN" | "PASS";

export interface Result {
  level: Level;
  name: string;
  detail: string;
}

export interface ColumnType {
  type?: number | null;
  referenceType?: number | null;
  referenceTypeName?: string | null;
  referenceTypeId?: string | null;
}

export interface Column {
  name?: string | null;
  path?: string | null;
  type?: ColumnType | null;
  customTemplate?: string | null;
}

export interface FormField {
  property?: { label?: string | null; name?: string | null } | null;
}

export interface WidgetSettings {
  name?: string | null;
  title?: string | null;
  columns?: Column[];
  fields?: FormField[];
  selectionMode?: number | null;
}

export interface Widget {
  id?: string;
  package?: string;
  name?: string;
  settings?: WidgetSettings | null;
}

export interface ActionButton {
  id?: string;
  settings?: {
    name?: string | null;
    buttonTitle?: string | null;
    iconClass?: string | null;
    actionId?: string | null;
    requiredFunctionality?: string | null;
  } | null;
}

export interface DataSource {
  id?: string;
  /** the component export name, e.g. "QueryDataSource" — not the instance name */
  name?: string;
  package?: string;
  settings?: { name?: string | null; query?: { Name?: string | null } | null } | null;
}

export interface LinkEnd {
  id?: string;
  type?: number;
}

export interface Link {
  source?: LinkEnd | string | null;
  target?: LinkEnd | string | null;
  output?: string | null;
  input?: string | null;
}

export interface PageSettings {
  widgets?: Widget[];
  links?: Link[];
  actionButtons?: ActionButton[];
  dataSources?: DataSource[];
  [key: string]: unknown;
}
