// =============================================================================
// On-the-Fly MCP Runtime — generic, hand-written MCP-over-HTTP server (Lambda).
//
// This is the FIXED, reviewed "shell" every on-the-fly MCP server runs on. It is
// NOT generated by the LLM. The only per-source thing it consumes is a MANIFEST
// (tools = name + inputSchema + read-only SELECT), baked into the deployment zip
// as manifest.json. In Phase 1 the LLM fills that manifest; the executable code
// here never changes.
//
// Speaks the subset of MCP JSON-RPC over HTTP that faborchestrator/lib/mcp-client.ts
// expects: initialize / tools/list / tools/call, an Mcp-Session-Id header, and a
// Bearer check. Postgres, read-only, guardrailed.
//
// ── GUARDRAILS (data + cost) ────────────────────────────────────────────────
//   • Bearer auth on every request (MCP_BEARER_TOKEN).                         → data
//   • Credentials never in env/code: fetched from Secrets Manager by ARN.      → data
//   • Read-only ONLY: every SQL must match ^(SELECT|WITH); a deny-list of
//     write/DDL keywords + multi-statement rejection; connection opened with
//     default_transaction_read_only=on.                                        → data
//   • Named params only ( :name → $n ), no string concatenation.              → data
//   • Row cap + output-byte cap + statement_timeout.                          → cost/data
//   • Warm-container reuse of the PG pool + cached secret.                     → cost
// =============================================================================

import { SecretsManagerClient, GetSecretValueCommand } from "@aws-sdk/client-secrets-manager";
import pg from "pg";
import { randomUUID } from "node:crypto";
import { RPC, rpcError, assertReadOnly, bindNamedParams, enforceLimit } from "./guard.mjs";

// ── config (all non-secret; secrets come from Secrets Manager) ──
const REGION = process.env.AWS_REGION || "us-west-2";
const SECRET_ARN = process.env.SECRET_ARN; // arn of the target DB creds
const BEARER = process.env.MCP_BEARER_TOKEN; // per-server bearer FO sends
const ROW_CAP = clampInt(process.env.MAX_ROWS, 1000, 1, 10000);
const OUTPUT_BYTE_CAP = clampInt(process.env.MAX_OUTPUT_BYTES, 1_000_000, 1024, 5_000_000);
const STATEMENT_TIMEOUT_MS = clampInt(process.env.STATEMENT_TIMEOUT_MS, 15000, 1000, 30000);
const PROTOCOL_VERSION = "2024-11-05";

// ── lazy singletons (reused across warm invocations) ──
let _sm = null;
let _secretCache = null; // { host, port, user, password, database, ssl? }
let _pool = null;
let _manifest = null;

function sm() {
  return (_sm ??= new SecretsManagerClient({ region: REGION }));
}

function clampInt(v, dflt, lo, hi) {
  const n = Number(v);
  if (!Number.isFinite(n)) return dflt;
  return Math.min(hi, Math.max(lo, Math.trunc(n)));
}

async function loadManifest() {
  if (_manifest) return _manifest;
  // manifest.json is baked into the deployment zip next to this file.
  const url = new URL("./manifest.json", import.meta.url);
  const { readFile } = await import("node:fs/promises");
  const raw = await readFile(url, "utf8");
  const parsed = JSON.parse(raw);
  if (!parsed || !Array.isArray(parsed.tools)) throw new Error("manifest.json missing tools[]");
  _manifest = parsed;
  return _manifest;
}

async function getSecret() {
  if (_secretCache) return _secretCache;
  if (!SECRET_ARN) throw new Error("SECRET_ARN is not configured");
  const res = await sm().send(new GetSecretValueCommand({ SecretId: SECRET_ARN }));
  if (!res.SecretString) throw new Error("target secret has no SecretString");
  const s = JSON.parse(res.SecretString);
  if (!s.host || !s.user || !s.password || !s.database) {
    throw new Error("target secret missing host/user/password/database");
  }
  _secretCache = { port: 5432, ...s };
  return _secretCache;
}

async function getPool() {
  if (_pool) return _pool;
  const s = await getSecret();
  _pool = new pg.Pool({
    host: s.host,
    port: Number(s.port) || 5432,
    user: s.user,
    password: s.password,
    database: s.database,
    ssl: s.ssl === false ? false : { rejectUnauthorized: false },
    max: 2,
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 10_000,
    // Every connection is forced read-only + bounded before any query runs.
    options: `-c default_transaction_read_only=on -c statement_timeout=${STATEMENT_TIMEOUT_MS}`,
  });
  return _pool;
}

async function runTool(tool, args) {
  const allowedKeys = Object.keys(tool.inputSchema?.properties || {});
  const safeSql = enforceLimit(assertReadOnly(tool.sql), ROW_CAP);
  const { bound, values } = bindNamedParams(safeSql, args, allowedKeys);
  const pool = await getPool();
  const result = await pool.query({ text: bound, values });
  let rows = result.rows.slice(0, ROW_CAP);
  const capped = result.rows.length > ROW_CAP;
  let text = JSON.stringify({ columns: result.fields.map((f) => f.name), rowCount: rows.length, capped, rows });
  if (Buffer.byteLength(text, "utf8") > OUTPUT_BYTE_CAP) {
    // Trim rows until under the byte cap.
    while (rows.length && Buffer.byteLength(text, "utf8") > OUTPUT_BYTE_CAP) {
      rows = rows.slice(0, Math.floor(rows.length / 2));
      text = JSON.stringify({ columns: result.fields.map((f) => f.name), rowCount: rows.length, capped: true, note: "output truncated to byte cap", rows });
    }
  }
  return { content: [{ type: "text", text }] };
}

// ── built-in health_check ──
// Proves the database answers: SELECT 1, then one row from the first table the
// manifest's first SQL reads (read-only guard + statement_timeout still apply).
const HEALTH_TOOL = {
  name: "health_check",
  description: "Connectivity check: opens the database connection and reads one row from the first table in the manifest.",
  inputSchema: { type: "object", properties: {} },
};
// First "FROM <ident>" of a query, kept only when it is a plain (optionally
// schema-qualified, optionally double-quoted) identifier — never interpolated otherwise.
function firstTableIn(sql) {
  const m = /\bFROM\s+((?:"[^"]+"|[A-Za-z_][A-Za-z0-9_$]*)(?:\.(?:"[^"]+"|[A-Za-z_][A-Za-z0-9_$]*))?)/i.exec(String(sql || ""));
  return m ? m[1] : null;
}
async function healthCheck(manifest) {
  const started = Date.now();
  const pool = await getPool();
  await pool.query("SELECT 1");
  const first = manifest.tools.find((t) => typeof t.sql === "string" && t.sql.trim());
  // A WITH query names CTEs first, which are not tables — only a plain SELECT is mined for one.
  const table = first && /^\s*SELECT\b/i.test(first.sql) ? firstTableIn(first.sql) : null;
  if (table) await pool.query(enforceLimit(assertReadOnly(`SELECT * FROM ${table}`), 1));
  return { content: [{ type: "text", text: JSON.stringify({ ok: true, db: "postgres", ms: Date.now() - started, table }) }] };
}

// ── MCP method handlers ──
async function handleRpc(body, sessionId) {
  const { id, method, params } = body;
  switch (method) {
    case "initialize":
      return ok(id, {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: { tools: {} },
        serverInfo: { name: "mcp-onthefly-runtime", version: "0.1.0" },
      });
    case "notifications/initialized":
      return null; // notification, no response
    case "tools/list": {
      const manifest = await loadManifest();
      const tools = manifest.tools.map((t) => ({
        name: t.name,
        description: t.description || `Read-only query: ${t.name}`,
        inputSchema: t.inputSchema || { type: "object", properties: {} },
      }));
      tools.push(HEALTH_TOOL);
      return ok(id, { tools });
    }
    case "tools/call": {
      const manifest = await loadManifest();
      const name = params?.name;
      if (name === HEALTH_TOOL.name) {
        try {
          return ok(id, await healthCheck(manifest));
        } catch (err) {
          // The driver's own message: a health check exists to say WHY the database is not answering.
          throw rpcError(RPC.INTERNAL, `health_check failed: ${err?.message || String(err)}`);
        }
      }
      const tool = manifest.tools.find((t) => t.name === name);
      if (!tool) throw rpcError(RPC.METHOD_NOT_FOUND, `Unknown tool: ${name}`);
      const result = await runTool(tool, params?.arguments || {});
      return ok(id, result);
    }
    default:
      throw rpcError(RPC.METHOD_NOT_FOUND, `Unknown method: ${method}`);
  }
}

// ── helpers ──
function ok(id, result) { return { jsonrpc: "2.0", id: id ?? null, result }; }
function errResponse(id, code, message) { return { jsonrpc: "2.0", id: id ?? null, error: { code, message } }; }

// ── Lambda entry point (Function URL / API GW v2 payload) ──
export const handler = async (event) => {
  const method = event?.requestContext?.http?.method || event?.httpMethod || "POST";
  const headers = lowerKeys(event?.headers || {});
  const respHeaders = { "content-type": "application/json" };

  if (method === "GET") {
    return { statusCode: 200, headers: respHeaders, body: JSON.stringify({ status: "ok", server: "mcp-onthefly-runtime" }) };
  }
  if (method !== "POST") {
    return { statusCode: 405, headers: respHeaders, body: JSON.stringify({ error: "method not allowed" }) };
  }

  // Bearer auth (constant work; do not leak which part failed).
  const auth = headers["authorization"] || "";
  if (!BEARER || auth !== `Bearer ${BEARER}`) {
    return { statusCode: 401, headers: respHeaders, body: JSON.stringify(errResponse(null, RPC.INVALID_REQUEST, "unauthorized")) };
  }

  let body;
  try {
    const raw = event.isBase64Encoded ? Buffer.from(event.body || "", "base64").toString("utf8") : (event.body || "");
    body = JSON.parse(raw);
  } catch {
    return { statusCode: 400, headers: respHeaders, body: JSON.stringify(errResponse(null, RPC.PARSE, "invalid JSON")) };
  }

  // Session id: echo the client's, or mint one on initialize.
  const sessionId = headers["mcp-session-id"] || randomUUID();
  respHeaders["mcp-session-id"] = sessionId;

  try {
    const result = await handleRpc(body, sessionId);
    if (result === null) return { statusCode: 202, headers: respHeaders, body: "" };
    return { statusCode: 200, headers: respHeaders, body: JSON.stringify(result) };
  } catch (err) {
    const code = err?.rpcCode || RPC.INTERNAL;
    // Never echo raw DB errors verbatim to avoid leaking schema/creds detail.
    const safeMsg = err?.rpcCode ? err.message : "internal error executing query";
    console.error(JSON.stringify({ level: "error", msg: err?.message, code, session: sessionId }));
    return { statusCode: 200, headers: respHeaders, body: JSON.stringify(errResponse(body?.id, code, safeMsg)) };
  }
};

function lowerKeys(obj) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) out[String(k).toLowerCase()] = v;
  return out;
}
